apiVersion: v1
kind: LimitRange
metadata:
  name: keda-compute-resources
  namespace: keda
spec:
  limits:
  - default:
      cpu: "200m"
      memory: "200Mi"
    defaultRequest:
      cpu: "100m"
      memory: "100Mi"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: keda-compute-resources
  namespace: keda
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "500Mi"
    limits.cpu: "2"
    limits.memory: "2Gi"