apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: tcp-metrics
  namespace: default  # 또는 적용할 네임스페이스
spec:
  metrics:
  - providers:
    - name: prometheus  # 사용할 메트릭 프로바이더 (기본값은 Prometheus)
    overrides:
    - match:
        destination_workload: "*"  # 모든 워크로드에 적용
        connection_protocol: "tcp"  # TCP 트래픽만 적용
      disabled: false  # TCP 메트릭 수집 활성화
