# Except Alertmanager

# Exclude - AKS Managed Component
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false

# Include - Kube-Proxy
# AKS 환경에 맞게 service.selector 설정
kubeProxy:
  enabled: true
  service:
    enabled: true
    port: 10249
    targetPort: 10249
    ipDualStack:
      enabled: false
      ipFamilies: ["IPv6", "IPv4"]
      ipFamilyPolicy: "PreferDualStack"
    selector:
      component: kube-proxy

# PrometheusRule
defaultRules:
  create: true
  rules:
    windows: false
    alertmanager: false

# Alertmanager
alertmanager:
  enabled: false

# Grafana
grafana:
  # Global Config
  defaultDashboardsTimezone: kst
  adminPassword: admin

  service:
    type: LoadBalancer
  
  # ServiceMonitor Setting
  serviceMonitor:
    enabled: true
    path: "/metrics"
    scrapeTimeout: 10s

  # Resource Requests/Limits
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  # node affinity
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: mgmt
            operator: In
            values:
            - monitoring
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"
  # StatefulSet Setting
  persistence:
    enabled: true
    type: sts
    storageClassName: azuredisk-ssd-lrs
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    finalizers:
      - kubernetes.io/pvc-protection
    # volumeName: restore-grafana-pv

# PrometheusOperator
prometheusOperator:
  admissionWebhooks:
    deployment:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"
    patch:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: mgmt
            operator: In
            values:
            - monitoring
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

# Promtetheus Server
prometheus:
  service:
    type: LoadBalancer
  # Prometheus Specs
  prometheusSpec:
    logLevel: info # debug
    
    # 메트릭 수집 설정
    scrapeInterval: "15s"
    evaluationInterval: "15s"
    scrapeTimeout: "10s"
    retention:  7d 
    retentionSize: "8GiB"

    # Namespace / Label 상관 없이 클러스터내 모든 PrometheusRule 식별
    ruleSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: {}
    ruleSelector: {}

    # Namespace / Label 상관 없이 클러스터내 모든 Pod Monitor 식별
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}

    # Namespace / Label 상관 없이 클러스터내 모든 Service Monitor 식별
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    
    
    # Replicas
    replicas: 1
    # node affinity
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: mgmt
              operator: In
              values:
              - monitoring
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"
    # Resource Requests / Limits
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    
    # StatefulSet Settings
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: azuredisk-ssd-lrs # 미리 단들어둔 스토리지클래스
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 8Gi
          # volumeName: restore-prometheus-pv # 복구용 PV 이름

# Node Exporter
# Resource Requests / Limits
nodeExporter:
  # Default Toleration 
  tolerations:
  - effect: NoSchedule
    operator: Exists
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Kube State Metrics
# node affinity
kube-state-metrics:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: mgmt
            operator: In
            values:
            - monitoring
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"
  # Resource Requests / Limits
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
