apiVersion: v1
kind: LimitRange
metadata:
  name: compute-resources
  namespace: monitoring
spec:
  limits:
  - default:
      cpu: "200m"
      memory: "200Mi"
    defaultRequest:
      cpu: "100m"
      memory: "100Mi"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: monitoring
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "4Gi"
    limits.cpu: "6"
    limits.memory: "8Gi"