# Note the API version is azmonitoring.coreos.com/v1 instead of monitoring.coreos.com/v1
apiVersion: azmonitoring.coreos.com/v1
kind: ServiceMonitor
# Can be deployed in any namespace
metadata:
  name: keda-operator-service-monitor
  namespace: keda
spec:
  # The selector filters endpoints by service labels.
  selector:
    matchLabels:
      app: keda-operator
  # Multiple endpoints can be specified. Port requires a named port.
  endpoints:
  - port: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: keda-operator-metrics
  namespace: keda
  labels:
    app: keda-operator
spec:
  selector:
    app: keda-operator
  ports:
  - port: 8080
    targetPort: 8080
    name: metrics
