---
apiVersion: v1
kind: Service
metadata:
  name: eventhub-consumer-metrics
  labels:
    app: eventhub-consumer
spec:
  selector:
    app: eventhub-consumer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: metrics
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eventhub-consumer-monitor
spec:
  selector:
    matchLabels:
      app: eventhub-consumer  # 서비스의 라벨과 일치해야 함
  namespaceSelector:
    matchNames:
      - default  # 서비스가 위치한 네임스페이스
  endpoints:
    - port: metrics  # 서비스에서 노출된 포트 이름
      path: /metrics  # 메트릭 경로
      interval: 15s  # 스크래핑 간격
      scrapeTimeout: 10s  # 타임아웃
